services:
  - type: web
    name: ethos-hrms
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ethos.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ethos-db
          property: connectionString

databases:
  - name: ethos-db
    plan: free
